# Generated by Django 4.2.9 on 2026-06-02 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('trains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scenario_type', models.CharField(choices=[('TRAIN_DELAY', 'Train Delay Simulation'), ('PLATFORM_FAILURE', 'Platform Failure'), ('MAINTENANCE_BLOCK', 'Maintenance Block'), ('SIGNAL_FAILURE', 'Signal Failure'), ('HEAVY_RAIN', 'Heavy Rain / Flooding'), ('ROUTE_CONGESTION', 'Route Congestion'), ('MASS_DELAY', 'Mass Delay Cascade'), ('CUSTOM', 'Custom Scenario')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('delay_minutes', models.IntegerField(default=30, help_text='Simulated delay in minutes')),
                ('duration_hours', models.FloatField(default=2.0, help_text='Scenario duration in hours')),
                ('simulation_speed', models.FloatField(default=1.0, help_text='1x = real time, 10x = 10x speed')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.TextField(blank=True)),
                ('throughput_impact', models.FloatField(blank=True, help_text='% throughput reduction', null=True)),
                ('trains_affected_count', models.IntegerField(blank=True, null=True)),
                ('estimated_recovery_time', models.IntegerField(blank=True, help_text='Minutes to recover', null=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('affected_sections', models.ManyToManyField(blank=True, to='stations.tracksection')),
                ('affected_stations', models.ManyToManyField(blank=True, to='stations.station')),
                ('affected_trains', models.ManyToManyField(blank=True, related_name='simulations', to='trains.train')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulation',
                'verbose_name_plural': 'Simulations',
                'db_table': 'simulations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulated_delay', models.IntegerField(default=0)),
                ('cascaded_delay', models.IntegerField(default=0)),
                ('status_change', models.CharField(blank=True, max_length=50)),
                ('platform_conflict', models.BooleanField(default=False)),
                ('track_conflict', models.BooleanField(default=False)),
                ('recommended_action', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='simulation.simulation')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_results', to='trains.train')),
            ],
            options={
                'db_table': 'simulation_results',
                'ordering': ['-simulated_delay'],
            },
        ),
    ]
