# Generated by Django 4.2.9 on 2026-06-02 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(db_index=True, max_length=10, unique=True)),
                ('train_name', models.CharField(max_length=100)),
                ('train_type', models.CharField(choices=[('RAJDHANI', 'Rajdhani Express'), ('SHATABDI', 'Shatabdi Express'), ('DURONTO', 'Duronto Express'), ('VANDE_BHARAT', 'Vande Bharat Express'), ('EXPRESS', 'Express'), ('MAIL', 'Mail'), ('PASSENGER', 'Passenger'), ('FREIGHT', 'Freight'), ('SPECIAL', 'Special')], default='EXPRESS', max_length=20)),
                ('speed', models.FloatField(default=100.0, help_text='Maximum speed in km/h')),
                ('priority_level', models.IntegerField(choices=[(1, 'Lowest'), (2, 'Low'), (3, 'Normal'), (4, 'High'), (5, 'Critical')], default=3)),
                ('rake_composition', models.CharField(blank=True, help_text='Coaches/wagons info', max_length=200)),
                ('total_coaches', models.IntegerField(default=12)),
                ('via_route', models.CharField(blank=True, help_text='Intermediate stations', max_length=500)),
                ('scheduled_departure', models.TimeField(blank=True, null=True)),
                ('scheduled_arrival', models.TimeField(blank=True, null=True)),
                ('days_of_operation', models.CharField(default='Daily', help_text='e.g., Mon,Wed,Fri or Daily', max_length=50)),
                ('current_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('DELAYED', 'Delayed'), ('ARRIVED', 'Arrived'), ('CANCELLED', 'Cancelled'), ('HELD', 'Held'), ('MAINTENANCE', 'Under Maintenance')], default='SCHEDULED', max_length=20)),
                ('current_delay', models.IntegerField(default=0, help_text='Delay in minutes')),
                ('last_known_location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trains', to=settings.AUTH_USER_MODEL)),
                ('destination_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminating_trains', to='stations.station')),
                ('source_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_trains', to='stations.station')),
            ],
            options={
                'verbose_name': 'Train',
                'verbose_name_plural': 'Trains',
                'db_table': 'trains',
                'ordering': ['train_number'],
                'indexes': [models.Index(fields=['train_number'], name='trains_train_n_28690f_idx'), models.Index(fields=['train_type'], name='trains_train_t_16749b_idx'), models.Index(fields=['current_status'], name='trains_current_7800f4_idx'), models.Index(fields=['priority_level'], name='trains_priorit_c65288_idx')],
            },
        ),
    ]
