# Generated by Django 4.2.9 on 2026-06-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_number', models.CharField(max_length=10)),
                ('platform_type', models.CharField(choices=[('ARRIVAL', 'Arrival'), ('DEPARTURE', 'Departure'), ('BOTH', 'Arrival & Departure'), ('GOODS', 'Goods')], default='BOTH', max_length=20)),
                ('length', models.FloatField(default=500.0, help_text='Platform length in meters')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance'), ('CLOSED', 'Closed')], default='AVAILABLE', max_length=20)),
                ('has_shelter', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'db_table': 'platforms',
                'ordering': ['station', 'platform_number'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distance', models.FloatField(help_text='Distance in kilometers')),
                ('estimated_duration', models.IntegerField(help_text='Estimated travel time in minutes')),
                ('via_stations', models.JSONField(blank=True, default=list, help_text='List of intermediate station codes')),
                ('max_speed', models.FloatField(default=130.0, help_text='Maximum permitted speed on route')),
                ('is_electrified', models.BooleanField(default=True)),
                ('is_double_line', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'db_table': 'routes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('station_type', models.CharField(choices=[('JUNCTION', 'Junction'), ('TERMINAL', 'Terminal'), ('HALT', 'Halt'), ('CROSSING', 'Crossing Station'), ('MAJOR', 'Major Station')], default='JUNCTION', max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zone', models.CharField(blank=True, help_text='Railway zone e.g. NR, NCR', max_length=50)),
                ('division', models.CharField(blank=True, max_length=50)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('total_platforms', models.IntegerField(default=1)),
                ('is_junction', models.BooleanField(default=False)),
                ('has_goods_shed', models.BooleanField(default=False)),
                ('has_fuel_point', models.BooleanField(default=False)),
                ('elevation', models.FloatField(default=0.0, help_text='Elevation in meters')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'db_table': 'stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('length', models.FloatField(help_text='Section length in kilometers')),
                ('number_of_lines', models.IntegerField(default=2, help_text='Number of parallel tracks')),
                ('max_speed', models.FloatField(default=130.0)),
                ('capacity', models.IntegerField(default=1, help_text='Max simultaneous trains')),
                ('status', models.CharField(choices=[('CLEAR', 'Clear'), ('OCCUPIED', 'Occupied'), ('BLOCKED', 'Blocked'), ('MAINTENANCE', 'Under Maintenance'), ('SIGNAL_FAILURE', 'Signal Failure')], default='CLEAR', max_length=20)),
                ('is_electrified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_from', to='stations.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_to', to='stations.station')),
            ],
            options={
                'verbose_name': 'Track Section',
                'verbose_name_plural': 'Track Sections',
                'db_table': 'track_sections',
                'ordering': ['code'],
            },
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['code'], name='stations_code_ebf9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['zone'], name='stations_zone_a70aca_idx'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='stations.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='source_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='stations.station'),
        ),
        migrations.AddField(
            model_name='platform',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='stations.station'),
        ),
        migrations.AddIndex(
            model_name='tracksection',
            index=models.Index(fields=['code'], name='track_secti_code_2395ec_idx'),
        ),
        migrations.AddIndex(
            model_name='tracksection',
            index=models.Index(fields=['status'], name='track_secti_status_1c3575_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together={('station', 'platform_number')},
        ),
    ]
