# Generated by Django 4.2.9 on 2026-06-02 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('stop_sequence', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('scheduled_arrival', models.DateTimeField(blank=True, null=True)),
                ('scheduled_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('arrival_delay', models.IntegerField(default=0, help_text='Delay in minutes (positive=late)')),
                ('departure_delay', models.IntegerField(default=0, help_text='Delay in minutes')),
                ('current_delay', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('ARRIVED', 'Arrived'), ('DEPARTED', 'Departed'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('DIVERTED', 'Diverted')], default='SCHEDULED', max_length=20)),
                ('halt_duration', models.IntegerField(default=2, help_text='Halt duration in minutes')),
                ('is_originating', models.BooleanField(default=False)),
                ('is_terminating', models.BooleanField(default=False)),
                ('distance_from_origin', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='stations.platform')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='stations.route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='stations.station')),
                ('track_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='stations.tracksection')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trains.train')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedules',
                'ordering': ['scheduled_date', 'scheduled_arrival'],
            },
        ),
        migrations.CreateModel(
            name='TrackOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('expected_exit_time', models.DateTimeField()),
                ('actual_exit_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_occupancies', to='scheduling.schedule')),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='stations.tracksection')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_occupancies', to='trains.train')),
            ],
            options={
                'verbose_name': 'Track Occupancy',
                'verbose_name_plural': 'Track Occupancies',
                'db_table': 'track_occupancies',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['scheduled_date'], name='schedules_schedul_100677_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status'], name='schedules_status_0e1604_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['train', 'scheduled_date'], name='schedules_train_i_c852ec_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['station', 'scheduled_date'], name='schedules_station_e939ad_idx'),
        ),
    ]
