# Generated by Django 4.2.9 on 2026-06-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_trains', models.IntegerField(default=0)),
                ('trains_running', models.IntegerField(default=0)),
                ('trains_delayed', models.IntegerField(default=0)),
                ('trains_cancelled', models.IntegerField(default=0)),
                ('trains_on_time', models.IntegerField(default=0)),
                ('avg_delay_minutes', models.FloatField(default=0.0)),
                ('max_delay_minutes', models.FloatField(default=0.0)),
                ('total_delay_minutes', models.FloatField(default=0.0)),
                ('section_throughput', models.FloatField(default=0.0, help_text='Trains/hour')),
                ('punctuality_rate', models.FloatField(default=0.0, help_text='% on time')),
                ('conflicts_detected', models.IntegerField(default=0)),
                ('conflicts_resolved', models.IntegerField(default=0)),
                ('platform_utilization', models.FloatField(default=0.0, help_text='% utilization')),
                ('track_utilization', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_snapshots',
                'ordering': ['-date'],
            },
        ),
    ]
