# Generated by Django 4.2.9 on 2026-06-02 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('trains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('TRACK', 'Track Conflict'), ('PLATFORM', 'Platform Conflict'), ('CROSSING', 'Crossing Conflict'), ('OCCUPANCY', 'Section Occupancy'), ('HEADWAY', 'Headway Violation')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('FALSE_ALARM', 'False Alarm')], default='ACTIVE', max_length=20)),
                ('conflict_time', models.DateTimeField(help_text='When the conflict occurs/occurred')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('resolution_notes', models.TextField(blank=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='stations.platform')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='stations.station')),
                ('track_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='stations.tracksection')),
                ('train_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_a', to='trains.train')),
                ('train_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_b', to='trains.train')),
            ],
            options={
                'verbose_name': 'Conflict',
                'verbose_name_plural': 'Conflicts',
                'db_table': 'conflicts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('PRIORITY', 'Train Priority Order'), ('HOLD', 'Hold Train'), ('CROSS', 'Crossing Order'), ('PLATFORM_CHANGE', 'Platform Change'), ('SPEED_ADJUST', 'Speed Adjustment'), ('ROUTE_DIVERT', 'Route Diversion')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IMPLEMENTED', 'Implemented')], default='PENDING', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reasoning', models.TextField(help_text='AI explanation for this recommendation')),
                ('priority_score', models.FloatField(default=5.0)),
                ('confidence', models.FloatField(default=0.85, help_text='Confidence 0-1')),
                ('estimated_benefit', models.CharField(blank=True, max_length=200)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_recommendations', to=settings.AUTH_USER_MODEL)),
                ('conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='conflicts.conflict')),
                ('primary_train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_recommendations', to='trains.train')),
                ('secondary_train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_recommendations', to='trains.train')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'db_table': 'recommendations',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['status'], name='recommendat_status_88bbb1_idx'), models.Index(fields=['generated_at'], name='recommendat_generat_c45ce2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conflict',
            index=models.Index(fields=['status'], name='conflicts_status_64953d_idx'),
        ),
        migrations.AddIndex(
            model_name='conflict',
            index=models.Index(fields=['severity'], name='conflicts_severit_7eab61_idx'),
        ),
        migrations.AddIndex(
            model_name='conflict',
            index=models.Index(fields=['conflict_type'], name='conflicts_conflic_0938ca_idx'),
        ),
        migrations.AddIndex(
            model_name='conflict',
            index=models.Index(fields=['detected_at'], name='conflicts_detecte_529c42_idx'),
        ),
    ]
