# Generated by Django 4.2.9 on 2026-06-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('THROUGHPUT', 'Throughput Optimization'), ('PRIORITY', 'Train Priority'), ('HOLDING', 'Holding Strategy'), ('CROSSING', 'Crossing Order'), ('REROUTING', 'Rerouting')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reasoning', models.TextField()),
                ('priority_score', models.FloatField(default=5.0)),
                ('confidence', models.FloatField(default=0.85)),
                ('is_active', models.BooleanField(default=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('affected_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.tracksection')),
            ],
            options={
                'db_table': 'ai_recommendations',
                'ordering': ['-generated_at'],
            },
        ),
    ]
