# Generated by Django 4.2.9 on 2026-06-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='primary_train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='trains.train'),
        ),
    ]
